import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

import QueryClientProviderWrapper from "@/providers/QueryClient";
import AuthButton from "@/components/AuthButton";
import Footer from "@/components/Footer";
import GridBackground from "@/components/shared/GridBackground";
import ScreenSizeIndicator from "@/components/shared/ScreenSizeIndicator";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <QueryClientProviderWrapper>
          <GridBackground />
          <div className="flex flex-col">
            <AuthButton />
            {children}
            <Footer />
          </div>
          <ScreenSizeIndicator />
          <ReactQueryDevtools />
          <Toaster />
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
