import type { Metadata } from "next";

import "./globals.css";

import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

import AuthProvider from "@/providers/AuthProvider";
import QueryClientProviderWrapper from "@/providers/QueryClient";
import Footer from "@/components/Footer";
import GridBackground from "@/components/shared/GridBackground";
import ScreenSizeIndicator from "@/components/shared/ScreenSizeIndicator";
import { Toaster } from "@/components/ui/toaster";
import UserAvatar from "@/components/user-avatar/UserAvatar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AuthProvider>
          <QueryClientProviderWrapper>
            <GridBackground />
            <div className="flex flex-col">
              <UserAvatar />
              {children}
              <Footer />
            </div>
            <ScreenSizeIndicator />
            <ReactQueryDevtools />
            <Toaster />
          </QueryClientProviderWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
